pipeline:
  identifier: Build_Junead2411_calculator_1701970483215
  name: Build calculator
  orgIdentifier: default
  projectIdentifier: project1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1701970453837
        repoName: Junead2411/calculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: calc-app
                  spec:
                    connectorRef: account.harnessImage
                    image: calctestimage
                    shell: Python
                    command: |+
                      # Python program for simple calculator

                      # Function to add two numbers
                      def add(num1, num2):
                          return num1 + num2

                      # Function to subtract two numbers
                      def subtract(num1, num2):
                          return num1 - num2

                      # Function to multiply two numbers
                      def multiply(num1, num2):
                          return num1 * num2

                      # Function to divide two numbers
                      def divide(num1, num2):
                          return num1 / num2

                      print("Please select operation -\n" \
                              "1. Add\n" \
                              "2. Subtract\n" \
                              "3. Multiply\n" \
                              "4. Divide\n")


                      # Take input from the user
                      select = int(input("Select operations form 1, 2, 3, 4 :"))

                      number_1 = int(input("Enter first number: "))
                      number_2 = int(input("Enter second number: "))

                      if select == 1:
                          print(number_1, "+", number_2, "=",
                                          add(number_1, number_2))

                      elif select == 2:
                          print(number_1, "-", number_2, "=",
                                          subtract(number_1, number_2))

                      elif select == 3:
                          print(number_1, "*", number_2, "=",
                                          multiply(number_1, number_2))


                      elif select == 4:
                          print(number_1, "/", number_2, "=",
                                          divide(number_1, number_2))
                      else:
                          print("Invalid input")


                    privileged: false
                    imagePullPolicy: Always
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
